# Generated by Django 4.2.3 on 2023-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='account',
            name='review',
            field=models.CharField(blank=True, default='REVIEW', max_length=100, null=True),
        ),
    ]
